### ISSUE TITLE
allow users to use the Arkime Lua plugin without having to create new bind volume mounts manually

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#533]
This came from **colby brooks** in the #Malcolm channel on the Arkime slack.

He was asking if there's a way to use the Arkime Lua plugin with Malcolm without having to manually bind-mount in a new config.ini file and the Lua files manually. I told him:

> probably ATM it's the former (bind in over the top of `/opt/arkime/etc/config.orig.ini` in the arkime container as well as doing a bind mount for the lua files).In the volumes section of the arkime service in the docker-compose it'd look something like this:
> 
```
     - type: bind
       bind:
         create_host_path: false
       source: ./arkime/etc/config.ini
       target: /opt/arkime/etc/config.orig.ini
       read_only: true
```
> Assuming your local config.ini is at ./arkime/etc/config.ini, if not just point to wherever it is. that's using the long volume syntax which we've recently switched to in the docker-compose, but you could also use the short syntax.

We ought to work out a way to automate this without having to make the user jump through these hoops.
