### ISSUE TITLE
OpenSearch Dashboards loads slowly without network connectivity

### ISSUE THREAD

**Issue by mmguero** [idaholab/Malcolm#75]
Due to the following section in `dashboards/opensearch_dashboards.yml`:

```
opensearchDashboards.branding:
  logo:
    defaultUrl: "https://raw.githubusercontent.com/idaholab/Malcolm/main/docs/images/logo/Malcolm_banner.png"
    darkModeUrl: "https://raw.githubusercontent.com/idaholab/Malcolm/main/docs/images/logo/Malcolm_outline_banner_dark.png"
  mark:
    defaultUrl: "https://raw.githubusercontent.com/idaholab/Malcolm/main/docs/images/icon/icon.png"
    darkModeUrl: "https://raw.githubusercontent.com/idaholab/Malcolm/main/docs/images/icon/icon_dark.png"
  faviconUrl: "https://raw.githubusercontent.com/idaholab/Malcolm/main/docs/images/favicon/facebook.png"
```
If there's no network connectivity Dashboards delays in loading waiting for the connection for the PNGs to time out. I need to figure out a way to host them locally.
